# Generated by Django 2.1.13 on 2019-10-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_myuser_check_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='integral',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
    ]
