# Generated by Django 2.1.13 on 2019-10-24 14:37

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_myuser_integral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='portrait',
            field=models.ImageField(default='image/default.jpg', upload_to=users.models.user_directory_path, verbose_name='头像'),
        ),
    ]
