# Generated by Django 2.1.13 on 2019-10-28 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191024_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='名称')),
                ('Parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.AreaInfo', verbose_name='父级名称')),
            ],
        ),
        migrations.CreateModel(
            name='TheContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='name')),
                ('city_addr', models.CharField(default='', max_length=50, verbose_name='所在地区')),
                ('address', models.CharField(default='', max_length=100, verbose_name='详细地址')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('zip_code', models.CharField(default='000000', max_length=6, verbose_name='邮政编码')),
                ('is_default', models.BooleanField(verbose_name='是否默认')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Myuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '常用联系人信息',
                'verbose_name_plural': '常用联系人信息',
            },
        ),
    ]
