# Generated by Django 2.1.13 on 2019-10-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_areainfo_thecontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='city',
        ),
        migrations.AddField(
            model_name='myuser',
            name='city_addr',
            field=models.CharField(default='410302', max_length=6, verbose_name='居住地代码'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(blank=True, default='1970-01-01', null=True, verbose_name='生日'),
        ),
    ]
